name: Pull Request

on:
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - main
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          make install-tools && make format && git diff --quiet
      - name: Stale constants
        run: make compile-constants && git diff --quiet

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}
      - name: Run Tests
        run: make test
